<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pricesproxy/prices_proxy.proto

namespace Productprices;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>productprices.ProductPricing</code>
 */
class ProductPricing extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .productprices.ProductPricing.Price currencies = 1;</code>
     */
    private $currencies;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Productprices\ProductPricing\Price[]|\Google\Protobuf\Internal\RepeatedField $currencies
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pricesproxy\PricesProxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .productprices.ProductPricing.Price currencies = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCurrencies()
    {
        return $this->currencies;
    }

    /**
     * Generated from protobuf field <code>repeated .productprices.ProductPricing.Price currencies = 1;</code>
     * @param \Productprices\ProductPricing\Price[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCurrencies($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Productprices\ProductPricing\Price::class);
        $this->currencies = $arr;

        return $this;
    }

}

