<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pricesproxy/prices_proxy.proto

namespace Productprices;

if (false) {
    /**
     * This class is deprecated. Use Productprices\ProductPricing\Price instead.
     * @deprecated
     */
    class ProductPricing_Price {}
}
class_exists(ProductPricing\Price::class);
@trigger_error('Productprices\ProductPricing_Price is deprecated and will be removed in the next major release. Use Productprices\ProductPricing\Price instead', E_USER_DEPRECATED);

