<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pricesproxy/prices_proxy.proto

namespace Productprices\ProductPricing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>productprices.ProductPricing.Price</code>
 */
class Price extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string currency = 1;</code>
     */
    private $currency = '';
    /**
     * Generated from protobuf field <code>int32 basePrice = 2;</code>
     */
    private $basePrice = 0;
    /**
     * Generated from protobuf field <code>int32 finalPrice = 3;</code>
     */
    private $finalPrice = 0;
    /**
     * Generated from protobuf field <code>int32 bonusWalletFunds = 4;</code>
     */
    private $bonusWalletFunds = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $currency
     *     @type int $basePrice
     *     @type int $finalPrice
     *     @type int $bonusWalletFunds
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pricesproxy\PricesProxy::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string currency = 1;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Generated from protobuf field <code>string currency = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 basePrice = 2;</code>
     * @return int
     */
    public function getBasePrice()
    {
        return $this->basePrice;
    }

    /**
     * Generated from protobuf field <code>int32 basePrice = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBasePrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->basePrice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 finalPrice = 3;</code>
     * @return int
     */
    public function getFinalPrice()
    {
        return $this->finalPrice;
    }

    /**
     * Generated from protobuf field <code>int32 finalPrice = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFinalPrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->finalPrice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 bonusWalletFunds = 4;</code>
     * @return int
     */
    public function getBonusWalletFunds()
    {
        return $this->bonusWalletFunds;
    }

    /**
     * Generated from protobuf field <code>int32 bonusWalletFunds = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setBonusWalletFunds($var)
    {
        GPBUtil::checkInt32($var);
        $this->bonusWalletFunds = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Price::class, \Productprices\ProductPricing_Price::class);

